language: ruby

env:
  global:
    - GIT_COMMITTER_NAME=turusuke
    - GIT_COMMITTER_EMAIL=mail@turusuke.com
    - GIT_AUTHOR_NAME=turusuke
    - GIT_AUTHOR_EMAIL=mail@turusuke.com
    - secure: dt/Tk/atT4kOuJpD1EHVO350NJgeE6RNOtf6zIMeHzNoRSFMzOLnb3Z2Z29zaGsupOWx1sw8AdPp9LTuLktW0mlxlwymdegVz6Iu3cXpohwqEtAHNk8MTPEHbnirBvL3jmrhM6ior1cdMnPqBv0Fa/5ABWJFb7HN6oKNSvSGlK4=

before_script:
    - git clone --quiet http://github.com/turusuke/middleman-build-test.git build
    - pushd build
    - git checkout -b gh-pages
    - popd

script:
    - bundle exec middleman build

after_success:
    - cd build
    - git add -A
    - git commit -m 'Update'
    - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/turusuke/middleman-build-test.git gh-pages 2> /dev/null'